# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Nathan A. Maldonado"

# A description of your site for meta tag, search engine results.
description: "I fell hard from somewhere not here"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://nathanamaldonado.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: About
    url: https://nathanamaldonado.github.io/about
  - text: Portfolio
    url: https://nathanamaldonado.github.io/portfolio


# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#f3bfcf'

# Site footer
footer:
  content: "&copy; Nathan A. Maldonado"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
